import { createStore } from 'vuex'

export default createStore({
  state: {
    users :[{
      "id": 1,
      "username": "trayman0",
      "phone": "173-249-5944",
      "email": "sklimpke0@japanpost.jp",
      "gender": "Male"
    }, {
      "id": 2,
      "username": "bgrichukhin1",
      "phone": "543-309-3279",
      "email": "bliepins1@ifeng.com",
      "gender": "Female"
    }, {
      "id": 3,
      "username": "santhon2",
      "phone": "798-989-8522",
      "email": "cstirgess2@shop-pro.jp",
      "gender": "Male"
    }, {
      "id": 4,
      "username": "egovett3",
      "phone": "648-492-3551",
      "email": "modriscoll3@wordpress.org",
      "gender": "Male"
    }, {
      "id": 5,
      "username": "tmoreby4",
      "phone": "278-744-7957",
      "email": "jgerrietz4@nytimes.com",
      "gender": "Male"
    }, {
      "id": 6,
      "username": "cmaleney5",
      "phone": "727-186-6816",
      "email": "amaccafferky5@archive.org",
      "gender": "Female"
    }, {
      "id": 7,
      "username": "cmatieu6",
      "phone": "657-272-2930",
      "email": "higgalden6@techcrunch.com",
      "gender": "Female"
    }, {
      "id": 8,
      "username": "hgozzard7",
      "phone": "569-358-7188",
      "email": "wdoret7@sourceforge.net",
      "gender": "Male"
    }, {
      "id": 9,
      "username": "rsteptow8",
      "phone": "671-526-1291",
      "email": "kwaterson8@bloomberg.com",
      "gender": "Female"
    }, {
      "id": 10,
      "username": "tbauchop9",
      "phone": "611-849-8671",
      "email": "gvagges9@csmonitor.com",
      "gender": "Female"
    }, {
      "id": 11,
      "username": "agoodboddya",
      "phone": "246-224-4948",
      "email": "csurmanwellsa@networksolutions.com",
      "gender": "Male"
    }, {
      "id": 12,
      "username": "vbrasseb",
      "phone": "726-127-4861",
      "email": "rkollasb@topsy.com",
      "gender": "Male"
    }, {
      "id": 13,
      "username": "fdimitrescoc",
      "phone": "229-660-6810",
      "email": "hantliffc@shop-pro.jp",
      "gender": "Genderqueer"
    }, {
      "id": 14,
      "username": "aelgeyd",
      "phone": "812-289-3597",
      "email": "gopied@last.fm",
      "gender": "Bigender"
    }, {
      "id": 15,
      "username": "vadolfe",
      "phone": "687-138-7745",
      "email": "glightmane@livejournal.com",
      "gender": "Female"
    }, {
      "id": 16,
      "username": "ctrayesf",
      "phone": "982-793-0068",
      "email": "ljovasevicf@printfriendly.com",
      "gender": "Male"
    }, {
      "id": 17,
      "username": "fguisbyg",
      "phone": "479-668-7576",
      "email": "echeshirg@chicagotribune.com",
      "gender": "Male"
    }, {
      "id": 18,
      "username": "adictyh",
      "phone": "538-434-9141",
      "email": "mrathboneh@accuweather.com",
      "gender": "Female"
    }, {
      "id": 19,
      "username": "gdawkesi",
      "phone": "568-713-6382",
      "email": "dcopellii@hexun.com",
      "gender": "Female"
    }, {
      "id": 20,
      "username": "apaigej",
      "phone": "317-111-3900",
      "email": "nwilmorej@ustream.tv",
      "gender": "Male"
    }, {
      "id": 21,
      "username": "aaikettk",
      "phone": "326-420-5136",
      "email": "nricoldk@reverbnation.com",
      "gender": "Female"
    }, {
      "id": 22,
      "username": "fmacgianyl",
      "phone": "239-751-7026",
      "email": "pfrancaisl@fema.gov",
      "gender": "Female"
    }, {
      "id": 23,
      "username": "skilbeem",
      "phone": "439-312-0564",
      "email": "iklimam@wufoo.com",
      "gender": "Genderqueer"
    }, {
      "id": 24,
      "username": "rdungayn",
      "phone": "146-384-7359",
      "email": "jallomn@cam.ac.uk",
      "gender": "Female"
    }, {
      "id": 25,
      "username": "jgallanto",
      "phone": "227-302-1908",
      "email": "grixo@hud.gov",
      "gender": "Male"
    }, {
      "id": 26,
      "username": "apeschmannp",
      "phone": "259-619-6964",
      "email": "nmatyasp@senate.gov",
      "gender": "Male"
    }, {
      "id": 27,
      "username": "ebrindleyq",
      "phone": "966-520-2151",
      "email": "lnisotq@ovh.net",
      "gender": "Female"
    }, {
      "id": 28,
      "username": "acalafater",
      "phone": "556-270-8684",
      "email": "ddavidowichr@addthis.com",
      "gender": "Male"
    }, {
      "id": 29,
      "username": "pbutens",
      "phone": "598-794-2984",
      "email": "areddells@taobao.com",
      "gender": "Male"
    }, {
      "id": 30,
      "username": "tsivetert",
      "phone": "390-329-1937",
      "email": "vloblet@meetup.com",
      "gender": "Female"
    }, {
      "id": 31,
      "username": "sdevittu",
      "phone": "775-194-1627",
      "email": "jrintoulu@infoseek.co.jp",
      "gender": "Female"
    }, {
      "id": 32,
      "username": "warchiboldv",
      "phone": "396-248-4472",
      "email": "roggerv@technorati.com",
      "gender": "Male"
    }, {
      "id": 33,
      "username": "hcawcuttw",
      "phone": "951-274-4683",
      "email": "ozuppaw@patch.com",
      "gender": "Bigender"
    }, {
      "id": 34,
      "username": "rjonczykx",
      "phone": "467-870-7469",
      "email": "lferrullix@cbc.ca",
      "gender": "Female"
    }, {
      "id": 35,
      "username": "mbonhany",
      "phone": "226-508-6862",
      "email": "ddanielskiy@feedburner.com",
      "gender": "Female"
    }, {
      "id": 36,
      "username": "dlebondz",
      "phone": "179-685-5043",
      "email": "bmunehayz@freewebs.com",
      "gender": "Female"
    }, {
      "id": 37,
      "username": "lgalea10",
      "phone": "471-763-3973",
      "email": "rosichev10@dot.gov",
      "gender": "Male"
    }, {
      "id": 38,
      "username": "hnote11",
      "phone": "515-748-4002",
      "email": "lswayland11@meetup.com",
      "gender": "Male"
    }, {
      "id": 39,
      "username": "klobbe12",
      "phone": "521-320-4550",
      "email": "bfarnon12@tripod.com",
      "gender": "Male"
    }, {
      "id": 40,
      "username": "nfelkin13",
      "phone": "797-403-6419",
      "email": "cgillson13@lycos.com",
      "gender": "Female"
    }, {
      "id": 41,
      "username": "malcide14",
      "phone": "541-190-5579",
      "email": "cdandison14@scribd.com",
      "gender": "Male"
    }, {
      "id": 42,
      "username": "ccolisbe15",
      "phone": "753-538-7904",
      "email": "edemullett15@wikispaces.com",
      "gender": "Female"
    }, {
      "id": 43,
      "username": "tbutterley16",
      "phone": "307-617-5501",
      "email": "tbrideoke16@yale.edu",
      "gender": "Male"
    }, {
      "id": 44,
      "username": "kbousler17",
      "phone": "307-957-6317",
      "email": "disoldi17@desdev.cn",
      "gender": "Female"
    }, {
      "id": 45,
      "username": "alegrave18",
      "phone": "697-441-8159",
      "email": "apinyon18@wp.com",
      "gender": "Female"
    }, {
      "id": 46,
      "username": "gdevaan19",
      "phone": "603-177-3819",
      "email": "mvicioso19@yellowbook.com",
      "gender": "Male"
    }, {
      "id": 47,
      "username": "lcrossfield1a",
      "phone": "876-187-8514",
      "email": "mlinacre1a@ihg.com",
      "gender": "Female"
    }, {
      "id": 48,
      "username": "darton1b",
      "phone": "954-913-5811",
      "email": "jiorio1b@dropbox.com",
      "gender": "Male"
    }, {
      "id": 49,
      "username": "rabrahamowitcz1c",
      "phone": "278-739-9829",
      "email": "jdennerley1c@gizmodo.com",
      "gender": "Male"
    }, {
      "id": 50,
      "username": "cbroe1d",
      "phone": "334-831-8342",
      "email": "gerrol1d@twitter.com",
      "gender": "Female"
    }, {
      "id": 51,
      "username": "ldellenbach1e",
      "phone": "149-283-2670",
      "email": "gsoonhouse1e@timesonline.co.uk",
      "gender": "Female"
    }, {
      "id": 52,
      "username": "sjiru1f",
      "phone": "359-395-2120",
      "email": "hgriffoen1f@diigo.com",
      "gender": "Male"
    }, {
      "id": 53,
      "username": "kjoselin1g",
      "phone": "453-225-7482",
      "email": "sfieldsend1g@timesonline.co.uk",
      "gender": "Male"
    }, {
      "id": 54,
      "username": "tfraczek1h",
      "phone": "549-188-9321",
      "email": "btreverton1h@yahoo.com",
      "gender": "Male"
    }, {
      "id": 55,
      "username": "sbohike1i",
      "phone": "341-168-8085",
      "email": "tbartoszek1i@forbes.com",
      "gender": "Male"
    }, {
      "id": 56,
      "username": "tshorrock1j",
      "phone": "313-622-1239",
      "email": "hbullen1j@homestead.com",
      "gender": "Female"
    }, {
      "id": 57,
      "username": "vrevill1k",
      "phone": "157-986-2370",
      "email": "cfylan1k@cnbc.com",
      "gender": "Male"
    }, {
      "id": 58,
      "username": "adaouse1l",
      "phone": "708-209-4794",
      "email": "srameaux1l@nasa.gov",
      "gender": "Female"
    }, {
      "id": 59,
      "username": "ezuenelli1m",
      "phone": "399-677-4808",
      "email": "eleacock1m@utexas.edu",
      "gender": "Genderfluid"
    }, {
      "id": 60,
      "username": "rmulqueen1n",
      "phone": "706-106-6165",
      "email": "mriddett1n@nasa.gov",
      "gender": "Female"
    }, {
      "id": 61,
      "username": "hgiraudoux1o",
      "phone": "451-450-3465",
      "email": "ballom1o@jiathis.com",
      "gender": "Female"
    }, {
      "id": 62,
      "username": "agenney1p",
      "phone": "781-532-7690",
      "email": "critmeyer1p@alexa.com",
      "gender": "Male"
    }, {
      "id": 63,
      "username": "rshearmer1q",
      "phone": "171-299-6517",
      "email": "gwombwell1q@deviantart.com",
      "gender": "Female"
    }, {
      "id": 64,
      "username": "sduckinfield1r",
      "phone": "105-352-2152",
      "email": "rkirkup1r@springer.com",
      "gender": "Male"
    }, {
      "id": 65,
      "username": "hwadman1s",
      "phone": "939-329-2753",
      "email": "cstoacley1s@cnn.com",
      "gender": "Female"
    }, {
      "id": 66,
      "username": "hmcsorley1t",
      "phone": "609-370-8911",
      "email": "mmillett1t@creativecommons.org",
      "gender": "Agender"
    }, {
      "id": 67,
      "username": "twinterbottom1u",
      "phone": "981-671-2281",
      "email": "cwalrond1u@icio.us",
      "gender": "Male"
    }, {
      "id": 68,
      "username": "dpitney1v",
      "phone": "678-930-6316",
      "email": "cslowey1v@tinypic.com",
      "gender": "Female"
    }, {
      "id": 69,
      "username": "dfawdery1w",
      "phone": "163-820-0543",
      "email": "mguppey1w@wikia.com",
      "gender": "Male"
    }, {
      "id": 70,
      "username": "pferroli1x",
      "phone": "841-371-3835",
      "email": "cbidgood1x@unesco.org",
      "gender": "Male"
    }, {
      "id": 71,
      "username": "cproudley1y",
      "phone": "478-257-8554",
      "email": "ffilpo1y@cmu.edu",
      "gender": "Female"
    }, {
      "id": 72,
      "username": "aannis1z",
      "phone": "302-206-0564",
      "email": "fmulrenan1z@admin.ch",
      "gender": "Female"
    }, {
      "id": 73,
      "username": "jsampey20",
      "phone": "300-696-3684",
      "email": "mhaysman20@aboutads.info",
      "gender": "Female"
    }, {
      "id": 74,
      "username": "dmckelvey21",
      "phone": "989-861-1900",
      "email": "mbingall21@hugedomains.com",
      "gender": "Female"
    }, {
      "id": 75,
      "username": "gsealove22",
      "phone": "150-312-5410",
      "email": "afillimore22@freewebs.com",
      "gender": "Female"
    }, {
      "id": 76,
      "username": "lgjerde23",
      "phone": "984-667-4194",
      "email": "zcomfort23@tinyurl.com",
      "gender": "Female"
    }, {
      "id": 77,
      "username": "nstollberger24",
      "phone": "573-984-6417",
      "email": "rmarkushkin24@slideshare.net",
      "gender": "Female"
    }, {
      "id": 78,
      "username": "oleeder25",
      "phone": "149-980-4379",
      "email": "oeslinger25@bluehost.com",
      "gender": "Female"
    }, {
      "id": 79,
      "username": "hdegnen26",
      "phone": "586-205-1701",
      "email": "wreavey26@ted.com",
      "gender": "Female"
    }, {
      "id": 80,
      "username": "nfranchioni27",
      "phone": "273-244-5537",
      "email": "bledster27@newyorker.com",
      "gender": "Female"
    }, {
      "id": 81,
      "username": "acaroli28",
      "phone": "674-839-5943",
      "email": "mbriddle28@friendfeed.com",
      "gender": "Female"
    }, {
      "id": 82,
      "username": "dpurchon29",
      "phone": "668-614-8220",
      "email": "hettels29@cargocollective.com",
      "gender": "Male"
    }, {
      "id": 83,
      "username": "lnester2a",
      "phone": "870-345-5316",
      "email": "vbeardsdale2a@posterous.com",
      "gender": "Female"
    }, {
      "id": 84,
      "username": "uhazeldene2b",
      "phone": "896-198-7411",
      "email": "sscholfield2b@symantec.com",
      "gender": "Female"
    }, {
      "id": 85,
      "username": "mboyton2c",
      "phone": "618-809-5086",
      "email": "njado2c@bloglovin.com",
      "gender": "Male"
    }, {
      "id": 86,
      "username": "ksmartman2d",
      "phone": "533-139-1527",
      "email": "ashoosmith2d@deviantart.com",
      "gender": "Male"
    }, {
      "id": 87,
      "username": "blant2e",
      "phone": "229-659-2165",
      "email": "ctrewhitt2e@examiner.com",
      "gender": "Female"
    }, {
      "id": 88,
      "username": "cgargett2f",
      "phone": "330-946-1764",
      "email": "fstallybrass2f@barnesandnoble.com",
      "gender": "Male"
    }, {
      "id": 89,
      "username": "ncalderbank2g",
      "phone": "808-768-4321",
      "email": "sfowls2g@weibo.com",
      "gender": "Female"
    }, {
      "id": 90,
      "username": "grathjen2h",
      "phone": "768-131-5129",
      "email": "dwybourne2h@narod.ru",
      "gender": "Male"
    }, {
      "id": 91,
      "username": "vroman2i",
      "phone": "872-606-9201",
      "email": "lmoxley2i@people.com.cn",
      "gender": "Male"
    }, {
      "id": 92,
      "username": "mbalog2j",
      "phone": "642-209-2624",
      "email": "eswinburn2j@artisteer.com",
      "gender": "Male"
    }, {
      "id": 93,
      "username": "vbraybrooks2k",
      "phone": "952-210-4061",
      "email": "nclifton2k@mit.edu",
      "gender": "Male"
    }, {
      "id": 94,
      "username": "civimey2l",
      "phone": "817-404-4288",
      "email": "snatte2l@clickbank.net",
      "gender": "Female"
    }, {
      "id": 95,
      "username": "sandreia2m",
      "phone": "918-398-4806",
      "email": "vgrayshan2m@census.gov",
      "gender": "Genderqueer"
    }, {
      "id": 96,
      "username": "dsummerill2n",
      "phone": "422-129-5230",
      "email": "ealmeida2n@histats.com",
      "gender": "Female"
    }, {
      "id": 97,
      "username": "gpaulton2o",
      "phone": "252-627-7672",
      "email": "lminkin2o@free.fr",
      "gender": "Male"
    }, {
      "id": 98,
      "username": "meberz2p",
      "phone": "365-765-1885",
      "email": "mstoggell2p@intel.com",
      "gender": "Male"
    }, {
      "id": 99,
      "username": "cshurmore2q",
      "phone": "268-880-9786",
      "email": "ptimewell2q@intel.com",
      "gender": "Female"
    }, {
      "id": 100,
      "username": "bandriuzzi2r",
      "phone": "250-417-4391",
      "email": "ccramond2r@canalblog.com",
      "gender": "Female"
    }],
    home:true,
    userId:null,
  },
  getters: {
  },
  mutations: {
    toNextPage(state,id){
      state.home=false;
      state.userId=id
    },
    BackTo(state){
      state.home=true
    }
  },
  actions: {
  },
  modules: {
  }
})
